# Generated by Django 4.2.14 on 2024-10-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedstored', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
