# Generated by Django 4.2.14 on 2024-10-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta', '0002_feeddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeddata',
            name='related_word',
            field=models.CharField(default='', max_length=30),
        ),
    ]
