# Generated by Django 4.2.14 on 2024-10-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta', '0003_feeddata_related_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeddata',
            name='browsed_word',
            field=models.CharField(default='', max_length=30),
        ),
    ]
