# Generated by Django 4.2.14 on 2024-10-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta', '0005_remove_feeddata_browsed_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='BData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(default='', max_length=30)),
                ('comment', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
